// Generated by tools/build-trees.py: impostor card per variant, [width, height, bottom] in metres at scale 1, atlas cell
// (256 x 512 cells of assets/textures/foliage/impostors.webp, 4 across, 3 rows, row 0 at the top).
export const IMPOSTOR = {"birch0": [10.815, 18.214, -0.408, 0], "birch1": [9.562, 19.988, -0.424, 1], "broad0": [12.631, 16.372, -0.414, 2], "broad1": [13.789, 14.961, -0.424, 3], "spruce0": [7.328, 20.2, -0.407, 4], "spruce1": [6.914, 17.89, -0.407, 5], "scots0": [14.138, 22.253, -0.438, 6], "scots1": [15.965, 19.922, -0.468, 7], "scots2": [18.466, 24.038, -0.438, 8], "bush0": [4.913, 4.099, -1.148, 9]};
export const IMPOSTOR_ROWS = 3;
// Physics record per species at scale 1, averaged over its variants: trunk radius at ~1 m, the height the disc can hit the trunk
// to, crown centre height (the leaves' mean height) and crown radius (between the crown's half-width and half-height).
export const TREE_DIMS = {"birch": [0.25, 15.97, 12.06, 3.6], "broad": [0.46, 8.55, 9.74, 4.32], "spruce": [0.38, 15.94, 10.06, 4.93], "scots": [0.45, 17.08, 14.97, 4.81]};
