// Generated by tools/build-trees.py: impostor card per variant, [width, height, bottom] in metres at scale 1, atlas cell
// (256 x 512 cells of assets/textures/foliage/impostors.webp, 4 across, 3 rows, row 0 at the top).
export const IMPOSTOR = {"birch0": [10.132, 18.246, -0.408, 0], "birch1": [8.728, 19.111, -0.421, 1], "broad0": [14.159, 15.638, -0.433, 2], "broad1": [15.957, 15.991, -0.414, 3], "spruce0": [6.929, 20.197, -0.405, 4], "spruce1": [6.438, 17.955, -0.405, 5], "scots0": [19.384, 22.188, -0.441, 6], "scots1": [12.77, 19.683, -0.457, 7], "scots2": [17.488, 23.25, -0.463, 8], "bush0": [4.817, 3.869, -1.199, 9]};
export const IMPOSTOR_ROWS = 3;
// Physics record per species at scale 1, averaged over its variants: trunk radius at ~1 m, the height the disc can hit the trunk
// to, crown centre height (the leaves' mean height) and crown radius (between the crown's half-width and half-height).
export const TREE_DIMS = {"birch": [0.25, 15.97, 12.06, 3.64], "broad": [0.46, 8.55, 9.82, 4.33], "spruce": [0.38, 15.94, 9.59, 4.93], "scots": [0.45, 17.08, 14.82, 4.67]};
